[package]
name = "Phos"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1", features = ["full"] }
sha2 = "0.10.9"
dotenv = "0.15"
